spring:
  application:
    name: feign-client

server:
  port: 2226

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/,http://localhost:8083/eureka/

feign:
  hystrix:
    enabled: true