spring:
  application:
    name: ribbonservice

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/,http://localhost:8083/eureka/

---

spring:
  profiles: r1
server:
  port: 2223
my:
  mark: ------------------eee------------------

---

spring:
  profiles: r2
server:
  port: 2224
my:
  mark: ------------------fff------------------