# 请求配置
server:
  port: 3350
  servlet:
    context-path: /learn11

# rabbitmq配置
spring:
  rabbitmq:
    username: zhigushuo
    password: zhigushuo
    host: localhost
    port: 5672
    virtual-host: /
    # 手动ACK 不开启自动ACK模式,目的是防止报错后未正确处理消息丢失 默认 为 none
    listener:
      simple:
        acknowledge-mode: manual
