server:
  port: 7725

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUniCode=true&characterEncoding=UTF-8&zeroDataTimeBehavior=round&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root